### ISSUE TITLE
Potentially rename package from MachineLearningMetrics.jl to MLMetrics.jl

### ISSUE THREAD

**Issue by paulhendricks** [JuliaML/MLMetrics.jl#13]
Currently an issue is open in METADATA.jl. It is unlikely that this is possible but worth a shot...

Issue can be found here: https://github.com/JuliaLang/METADATA.jl/issues/4951

**Comment by paulhendricks** [comment]
Solution:
- I will deprecate MachineLearningMetrics.jl and keep it under paulhendricks/MachineLearningMetrics.jl.
- I will register a new package MLMetrics.jl with METADATA.jl and point it to JuliaML/MLMetrics.jl.

**Comment by tbreloff** [comment]
This sounds like the best solution!

**Comment by Evizero** [comment]
:+1: don't forget to update all the files in your root directory (travis, license etc) accordingly.

**Comment by paulhendricks** [comment]
@Evizero Will do.

**Comment by paulhendricks** [comment]
Updated all files. Creating separate issue to register, tag, and publish MLMetrics.jl.
