### ISSUE TITLE
ROC / PR curves

### ISSUE THREAD

**Issue by pevnak** [JuliaML/MLMetrics.jl#20]
Hi,

are there any plans to include ROC or PR curves? I know about separate packages providing this functionality, but they do not seem to be well maintained. Would you welcome PR on this?

**Comment by Evizero** [comment]
I am unsure. there is rich ROC package out there already, although I'll admit it is a bit awkward for ML purposes. 

I think ROC code could live here, but I have not thought about how it should look. 

If you are interested in trying out a PR I'd happily review it, but be prepared for a lot of emerging design discussions.

**Comment by pevnak** [comment]
Ok,

I might start to think about something. I would not mind design discussions, as I would like to learn something. I will sketch something.

**Comment by Evizero** [comment]
i added a basic ROC curve here
