### ISSUE TITLE
Package does not exists in METADATA

### ISSUE THREAD

**Issue by asbisen** [JuliaML/MLMetrics.jl#26]
It seems the package is not registered in `METADATA.jl`

```julia
(v1.0) pkg> add MLMetrics
ERROR: The following package names could not be resolved:
 * MLMetrics (not found in project, manifest or registry)
Please specify by known `name=uuid`.

```

**Comment by Evizero** [comment]
I was a bit overly optimistic when writing the readme. changed it now

https://github.com/JuliaML/MLMetrics.jl/commit/a056626eeb01c89e6b1436a4811131f8f24e8e49
